{% set name = "qtkeychain" %}
{% set version = "0.9.0" %}
{% set sha256 = "0935e5eb67fbed0b2db5e74ea8cbd667c6be6eed3767f212eac6ac318ab8a6fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/frankosterfeld/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain.so  # [linux]
    - test -f ${PREFIX}/lib/libqt5keychain.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: Modified BSD
  license_file: COPYING
  summary: 'QtKeychain is a Qt API to store passwords and other secret data securely'

extra:
  recipe-maintainers:
    - ceholden
    - gillins
