{% set name = "qtkeychain" %}
{% set version = "0.9.1" %}
{% set sha256 = "9c2762d9d0759a65cdb80106d547db83c6e9fdea66f1973c6e9014f867c6f28e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/frankosterfeld/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # FIXME: On Win, expansion fails due to 'ReadMe.markdown' symlink in archive.
  #        Find automated way of stripping it, or save to other endpoint as cleaned archive.

build:
  number: 1000

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt 5.9.*
  run:
    - qt 5.9.*

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain.so  # [linux]
    - test -f ${PREFIX}/lib/libqt5keychain.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: Modified BSD
  license_file: COPYING
  summary: 'QtKeychain is a Qt API to store passwords and other secret data securely'

extra:
  recipe-maintainers:
    - ceholden
    - gillins
    - dakcarto
