appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MChtkPJ/BvI8J0LZe+36BaJIIZNN2NtMPVVAvnlNszgJ98K2qQ6W6WPhSixq9wqvkW0+6Gnwp1Hu/tpe6V9JIJXY1Xe6w2gA4TO6FWFKSiGiy1JL25FJvBPyXstQXABsy6T+ZSVM46ziHOc3kzQFOnSAUSsKTauKq3K1jB0lrNaCehlCh9T/xr+T8ffs1aulGe0GPGxb5L3U7poN8EJ6Bik3Yj3c/0rprMI7lsqsegDOK6qP3DvetpwTkrlaq+i9/4qS/2m7nCA1KMyTBHsz+TLAtVfeAHYHR0/ieBR83myqH/OOK6amND3Yru/6sbx62Ld5UUJUaD7zAlUV0e0d+mrlIsnbyTwEPpIoJfSy+EnR5uQi2MaOF9IlPubXQXOithLKwW0BPPZsINO+YvLXrnoiIwE1N2FAHVQlvh03vSghwMFoCtc9votx19rscxv5YLVNKTMtrxDw6RVCBJwwxw7A+QePLxliK/ZOXAoq4fWFtQc+Yu2rePI0sbfD+T/UbClibZjxHTgFU87XBP5L92LdRNWeYm5T2kVXS+L4rGMtuDHs+vIltBmhihiW8RLOY3myeVTz7/iN2XFL4qsPZhO1EVARhnZ735aJTIg81/3Ayz33RCnZybzlLys5sgVkQvwqZ1H8solQm6nNTkjGu6Dan1Uug0hJqxGoZQy6SMI=}
